Repository malinclarsson/mandatory-project-agile1-, pull requests merged in 2020-01, with the labels that each got.

#46 Första enkelt HomeStyle
  frontend/src/Home.jsx
  frontend/src/components/Gameboard/ChessBoard.jsx
  frontend/src/components/Gameboard/styles.js
  frontend/src/components/Global/Chatt.jsx
  frontend/src/components/Global/style.js
  frontend/src/css/home.css
  frontend/src/index.css
  frontend/src/style.js
Labels: Design

#48 Veckans sprint v.3
  sprint_v.1.md
  sprint_v.2.md
  sprint_v.3.md
Labels: mötesanteckningar

#52 GameStatusHub Finished #51.
  frontend/src/components/Gameboard/ChessBoard.jsx
  frontend/src/components/Gameboard/GameStatusHub.jsx
  frontend/src/components/Gameboard/styles.js
Labels: Design

#50 Popup and login, closes #50
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Home.jsx
  frontend/src/components/Global/Popup.jsx
  frontend/src/components/Global/style.js
  frontend/src/components/Lobby/Room.jsx
  frontend/src/components/Lobby/style.js
  frontend/src/index.js
  frontend/src/style.js
Labels: frontend

#56 added sprint_v.4.md
  sprint_v.4.md
Labels: mötesanteckningar

#58 Satt upp grunden för backenden - Closes #18
  backend/.eslintrc.js
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/helpers/response.js
  backend/src/helpers/room.js
  backend/src/helpers/users.js
Labels: backend

#61 Sprint v.5 closes #14
  sprint_v.5.md
Labels: mötesanteckningar

#63 Game logic #54
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Gameboard/ChessBoard.jsx
  frontend/src/components/Gameboard/GameStatusHub.jsx
  frontend/src/components/Gameboard/Rough.js
  frontend/src/components/Gameboard/styles.js
  frontend/src/components/Home/style.js
Labels: Logic, frontend

#66 Fen skickas till server #53
  frontend/src/components/Gameboard/ChessBoard.jsx
  frontend/src/components/Gameboard/GameStatusHub.jsx
  frontend/src/components/Global/Chatt.jsx
Labels: frontend

#67 Issues/issue 35
  frontend/src/Home.jsx
  frontend/src/components/Global/Popup.jsx
  frontend/src/components/Home/ActiveGames.jsx
  frontend/src/components/Lobby/RoomList.jsx
  frontend/src/components/Lobby/style.js
  frontend/src/index.js
Labels: frontend

#70 Style-popup finished #69.
  frontend/src/components/Global/Popup.jsx
  frontend/src/components/Global/style.js
Labels: Design

#76 Style fixed #74
  frontend/src/Home.jsx
  frontend/src/components/Global/style.js
Labels: Design
